root: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"
plugins:
  - "@typescript-eslint/eslint-plugin"
  - "security"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:security/recommended"
  - "plugin:prettier/recommended"
rules:
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  eqeqeq:
    - error
    - always
  no-console: error

  # @typescript-eslint plugin
  "@typescript-eslint/no-unused-vars":
    - error
    - args: all
      argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"

  # prettier plugin
  "prettier/prettier":
    - error
    - singleQuote: false
      trailingComma: es5
      printWidth: 100
      tabWidth: 2
      semi: true
      bracketSpacing: true
      endOfLine: lf
