version: "3.0"
services:
  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend:/usr/src/app/packages/backend

  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./packages/web:/usr/src/app/packages/web
