version: "3.0"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend:/usr/src/app/packages/backend
      - ./packages/common:/usr/src/app/packages/common

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./packages/web:/usr/src/app/packages/web
      - ./packages/common:/usr/src/app/packages/common

  common:
    container_name: common
    build:
      context: .
      dockerfile: ./packages/common/Dockerfile
    volumes:
      - ./packages/common:/usr/src/app/packages/common
