settings:
  react:
    version: "detect"
env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
plugins:
  - react
rules:
  # @typescript-eslint plugin
  "@typescript-eslint/no-empty-function": off

  # React plugin
  "react/react-in-jsx-scope": "off"
  "react/no-unknown-property":
    - 2
    - ignore:
        - css
