#!/bin/sh
# create default user
set -eu

mysql -u root -p${MYSQL_ROOT_PASSWORD} <<EOSQL
CREATE USER '${MYSQL_DEFAULT_USER}' IDENTIFIED BY '${MYSQL_DEFAULT_PASSWORD}';
GRANT
  SELECT, INSERT, UPDATE, DELETE
  ON ${MYSQL_DATABASE}.* TO '${MYSQL_DEFAULT_USER}';

CREATE USER '${MYSQL_MIGRATION_USER}' IDENTIFIED BY '${MYSQL_MIGRATION__PASSWORD}';
GRANT
  SELECT, INSERT, UPDATE, DELETE
  ON ${MYSQL_DATABASE}.* TO '${MYSQL_MIGRATION_USER}';
GRANT
  CREATE, ALTER, DROP, REFERENCES
  ON *.* TO '${MYSQL_MIGRATION_USER}';
EOSQL
